theme: jekyll-theme-minimal

title: [Tilia Bell Codes]
description: ["Life Tip: You can do pretty much anything if you yell the right phrase"]
logo: ["https://github.com/tiliabell/tiliabell.github.io/blob/main/forscience-icon.png"]
